FROM node:16.13.2-alpine3.14
RUN npm install -g npm@8.19.2
WORKDIR /app
COPY package*.json ./

RUN npm install

RUN mkdir -p node_modules/.cache && chmod -R 777 node_modules/.cache

COPY . .

EXPOSE 3000

CMD ["npm", "run", "start"]